export const CONNECT_DEVICE_REQUEST = "Bluetooth/CONNECT_DEVICE_REQUEST"
export const CONNECT_DEVICE_SUCCESS = "Bluetooth/CONNECT_DEVICE_SUCCESS"
export const CONNECT_DEVICE_FAILURE = "Bluetooth/CONNECT_DEVICE_FAILURE"


export const SCAN_FOR_PERIPHERALS_REQUEST= "Bluetooth/SCAN_FOR_PERIPHERALS_REQUEST"
export const ON_DEVICE_DISCOVERED= "Bluetooth/ON_DEVICE_DISCOVERED"

export const START_HEART_RATE_SCAN_REQUEST = "Bluetooth/START_HEART_RATE_SCAN_REQUEST"
export const UPDATE_HEART_RATE_SUCCESS= "Bluetooth/UPDATE_HEART_RATE_SUCCESS"
export const UPDATE_HRV_SUCCESS= "Bluetooth/UPDATE_HRV_SUCCESS"
