export const SAMPLE_ACTION_REQUEST = "Common/SAMPLE_ACTION_REQUEST"
export const SAMPLE_ACTION_SUCCESS = "Common/SAMPLE_ACTION_SUCCESS"
export const SAMPLE_ACTION_CANCEL = "Common/SAMPLE_ACTION_CANCEL"
export const NAVIGATION_CHANGE = "Common/NAVIGATION_CHANGE"